### ISSUE TITLE
Filling `email` field on `/admin/forgot` causes an uncaught TypeError

### ISSUE THREAD

**Issue by klapec** [payloadcms/payload-3.0-alpha-demo#12]
Steps to reproduce:

1. Visit https://next-payload-3-0-test.vercel.app/admin/forgot
2. Focus the email field
3. Press any key

```
771-55ddd206a39b39f6.js:63 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at t.Z (771-55ddd206a39b39f6.js:63:61259)
    at 771-55ddd206a39b39f6.js:63:58011
    at 771-55ddd206a39b39f6.js:63:132337
    at 771-55ddd206a39b39f6.js:63:132651
    at 771-55ddd206a39b39f6.js:63:137920
```

**Comment by kendell-payload** [comment]
@klapec - just letting you know I am working on this fix, thank you for discovering this issue.
