### ISSUE TITLE
Upgrading from alpha.40 to alpha.41  breaks generate:types

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#21]
Upgrading from `alpha.40` to `alpha.41` breaks the ability to run `payload generate:types`, resulting in the following error:

```
$ payload generate:types
(node:57488) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///D:/.../node_modules/drizzle-kit/payload.mjs:13
  throw Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "net" is not supported
    at file:///D:/.../node_modules/drizzle-kit/payload.mjs:13:9
    at node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js (file:///D:/.../node_modules/drizzle-kit/payload.mjs:32619:15)
    at __require2 (file:///D:/.../node_modules/drizzle-kit/payload.mjs:19:50)
    at node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/index.js (file:///D:/.../node_modules/drizzle-kit/payload.mjs:33955:23)
    at __require2 (file:///D:/.../node_modules/drizzle-kit/payload.mjs:19:50)
    at node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/promise.js (file:///D:/.../node_modules/drizzle-kit/payload.mjs:34023:16)
    at __require2 (file:///D:/.../node_modules/drizzle-kit/payload.mjs:19:50)
    at file:///D:/.../node_modules/drizzle-kit/payload.mjs:36580:30
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)

Node.js v18.19.0
```

I'm using postgres. sort of wonder why I'm seeing `mysql` in those errors, but I'll leave that up to you guys 😅 Everything was working fine on `alpha.40`

**Comment by gnovotny** [comment]
I'm on `alpha.40` and I'm gettin the same error in a seeder that I'm running with `ts-node`, when calling `payload.init`. It seems to be an issue with drizzle-kit.

**Comment by jmikrut** [comment]
I think we can solve this - we are on it!

**Comment by jmikrut** [comment]
Hey all, this is now fixed and will be released in the next alpha!

Thank you for reporting. Keep 'em coming! We REALLY appreciate you all testing this with us.
