### ISSUE TITLE
Using a field type of "json" crashes the ListView UI

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#22]
Using Postgres, pnpm, latest `payload-3.0-alpha-demo`, all alpha versions are at `41`.

Adding the following to a collection's fields works fine on the individual document page:

```
    {
      name: "jsonTest",
      type: "json",
    },
```

However, when going back to my collection's list view (paginated table), I get a white screen and the following client devtools errors:

```
main-app.js?v=1710003264937:992 Warning: Cannot update a component (`HotReload`) while rendering a different component (`JSONCell`). To locate the bad setState() call inside `JSONCell`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at JSONCell (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.41_@types+react@18.2.64_http-status@1.6.2_monaco-editor@0.47.0_n_byv5ctekdhxgwgmcsqe7kjtcqa/node_modules/@payloadcms/next/dist/views/List/Default/Cell/fields/JSON/index.js:10:11)
    at span
    at DefaultCell (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.41_@types+react@18.2.64_http-status@1.6.2_monaco-editor@0.47.0_n_byv5ctekdhxgwgmcsqe7kjtcqa/node_modules/@payloadcms/next/dist/views/List/Default/Cell/index.js:22:13)
    at RenderCustomComponent (Server)
    at TableCellProvider (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.41_@types+react@18.2.64_monaco-editor@0.47.0_next@14.2.0-canary.10_vhdarcvh7s7zt25x34a6r7pun4/node_modules/@payloadcms/ui/dist/elements/Table/TableCellProvider/index.js:12:13)
...(many more lines)
```
```
index.js:11 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at JSONCell (index.js:11:33)
    at renderWithHooks (react-dom.development.js:11121:18)
    at mountIndeterminateComponent (react-dom.development.js:16869:13)
    at beginWork$1 (react-dom.development.js:18458:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at beginWork (react-dom.development.js:26949:7)
    at performUnitOfWork (react-dom.development.js:25748:12)
    at workLoopConcurrent (react-dom.development.js:25734:5)
    at renderRootConcurrent (react-dom.development.js:25690:9)
    at performConcurrentWorkOnRoot (react-dom.development.js:24504:38)
    at workLoop (scheduler.development.js:256:34)
    at flushWork (scheduler.development.js:225:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:534:21)
```

edit:
It should also be noted that if you enter any json in to the json field and save the document, it is not persisted. Nothing is saved.

**Comment by AlessioGr** [comment]
Thank you for reporting this! Fixed in 3.0.0-alpha.48 :)
