### ISSUE TITLE
Adding a Row via array field type causes unhandled runtime error

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#26]
Here is my array field:
```
  {
          label: "Mastery Nodes",
          fields: [
            {
              name: "masteryNodes",
              type: "array",
              labels: {
                singular: "Node",
                plural: "Nodes",
              },
              fields: [
                {
                  name: "title",
                  type: "text",
                  required: true,
                  localized: true,
                },
                {
                  name: "description",
                  type: "richText",
                  required: true,
                  localized: true,
                },
              ],
            },
          ],
        },
```
It appears to be with any inner field-type for the array. I switched richText with a text field for example. When I create an array field like that, initially, no errors occur until I restart my dev server. (Reference #25) Once the config/drizzle update goes in, from that point forward, array fields experience the following errors;

Next Error:
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'value')

Call Stack
eval
node_modules\.pnpm\@payloadcms+ui@3.0.0-alpha.41_@types+react@18.2.64_monaco-editor@0.47.0_next@14.2.0-canary.10_vhdarcvh7s7zt25x34a6r7pun4\node_modules\@payloadcms\ui\dist\forms\Form\mergeServerFormState.js (11:1)
Array.forEach
<anonymous>
mergeServerFormState
node_modules\.pnpm\@payloadcms+ui@3.0.0-alpha.41_@types+react@18.2.64_monaco-editor@0.47.0_next@14.2.0-canary.10_vhdarcvh7s7zt25x34a6r7pun4\node_modules\@payloadcms\ui\dist\forms\Form\mergeServerFormState.js (9:1)
fields
node_modules\.pnpm\@payloadcms+ui@3.0.0-alpha.41_@types+react@18.2.64_monaco-editor@0.47.0_next@14.2.0-canary.10_vhdarcvh7s7zt25x34a6r7pun4\node_modules\@payloadcms\ui\dist\forms\Form\index.js (465:68)
```

DevTools Error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at eval (mergeServerFormState.js:16:46)
    at Array.forEach (<anonymous>)
    at mergeServerFormState (mergeServerFormState.js:14:30)
    at executeOnChange (index.js:504:126)
...
```

**Database adapter:** Postgres
**Package Manager:** pnpm
**Payload Alpha Version:** 41
**Node Version:** 18.19.0
Using `payload-3.0-alpha-demo` example ✅

Video:
https://gyazo.com/0002b4969adf43b18c1a3aca195e7a4b

**Comment by paulpopus** [comment]
Hey @HarleySalas we just pushed a fix that handles array and block fields, can you let us know if you still experience this issue please?

**Comment by paulpopus** [comment]
Closing for now, please re-open if you manage to reproduce it!
