### ISSUE TITLE
Cannot read properties of undefined (reading 'referencedTable')

### ISSUE THREAD

**Issue by ThomasAunvik** [payloadcms/payload-3.0-alpha-demo#4]
Reproducable way: Editing the the payload.config.ts, just adding a comment or editing one, would cause this error:

```
[15:11:21] ERROR: TypeError: Cannot read properties of undefined (reading 'referencedTable')
    at normalizeRelation (webpack-internal:///(rsc)/./node_modules/drizzle-orm/relations.js:211:56)
    at PgDialect.buildRelationalQueryWithoutPK (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/dialect.js:963:101)
    at QueryPromise._getQuery (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:90:25)
    at QueryPromise._toSQL (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:105:24)
    at eval (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:69:42)
    at Object.startActiveSpan (webpack-internal:///(rsc)/./node_modules/drizzle-orm/tracing.js:14:14)
    at QueryPromise._prepare (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:68:60)
    at eval (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:114:19)
    at Object.startActiveSpan (webpack-internal:///(rsc)/./node_modules/drizzle-orm/tracing.js:14:14)
    at QueryPromise.execute (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:113:60)
    at QueryPromise.then (webpack-internal:///(rsc)/./node_modules/drizzle-orm/query-promise.js:26:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Unsure that the error has also occurred without editing that specific file. 

package.json

```json
{
  "name": "next-latest-starter",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "generate:types": "payload generate:types",
    "start": "next start",
    "lint": "next lint"
  },
  "engines": {
    "node": ">=18.17.0"
  },
  "dependencies": {
    "@payloadcms/db-mongodb": "3.0.0-alpha.34",
    "@payloadcms/db-postgres": "^3.0.0-alpha.34",
    "@payloadcms/next": "3.0.0-alpha.34",
    "@payloadcms/richtext-lexical": "3.0.0-alpha.34",
    "@payloadcms/richtext-slate": "3.0.0-alpha.34",
    "next": "14.2.0-canary.9",
    "payload": "3.0.0-alpha.34",
    "react": "^18",
    "react-dom": "^18",
    "sharp": "0.32.6"
  },
  "devDependencies": {
    "@biomejs/biome": "1.5.3-nightly.4fa841c",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.4.18",
    "dotenv": "^16.4.5",
    "eslint": "^8",
    "eslint-config-next": "14.1.0",
    "postcss": "^8.4.35",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}
```

**Comment by DanRibbens** [comment]
Try again with versions `v3.0.0-alpha.41`. This should be fixed. I'll reopen if we need to.

**Comment by ThomasAunvik** [comment]
Seems to be still an issue.

**Comment by ThomasAunvik** [comment]
```
⨯ Internal error: TypeError: Cannot read properties of undefined (reading 'referencedTable')
    at normalizeRelation (./node_modules/drizzle-orm/relations.js:211:56)
    at PgDialect.buildRelationalQueryWithoutPK (./node_modules/drizzle-orm/pg-core/dialect.js:963:101)
    at QueryPromise._getQuery (./node_modules/drizzle-orm/pg-core/query-builders/query.js:90:25)
    at QueryPromise._toSQL (./node_modules/drizzle-orm/pg-core/query-builders/query.js:105:24)
    at eval (./node_modules/drizzle-orm/pg-core/query-builders/query.js:69:42)
    at Object.startActiveSpan (./node_modules/drizzle-orm/tracing.js:14:14)
    at QueryPromise._prepare (./node_modules/drizzle-orm/pg-core/query-builders/query.js:68:60)
    at eval (./node_modules/drizzle-orm/pg-core/query-builders/query.js:114:19)
    at Object.startActiveSpan (./node_modules/drizzle-orm/tracing.js:14:14)
    at QueryPromise.execute (./node_modules/drizzle-orm/pg-core/query-builders/query.js:113:60)
    at QueryPromise.then (./node_modules/drizzle-orm/query-promise.js:26:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
digest: "1975018096"````
