### ISSUE TITLE
unknown system error -8 spawn on npm run dev

### ISSUE THREAD

**Issue by fpolli** [payloadcms/payload-3.0-alpha-demo#47]
> next-latest-starter@0.1.0 dev
> cross-env NODE_OPTIONS=--no-deprecation next dev

node:internal/child_process:421
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at spawn (/payload-3.0-alpha-demo/node_modules/cross-spawn/index.js:12:24)
    at crossEnv (/payload-3.0-alpha-demo/node_modules/cross-env/src/index.js:13:18)
    at Object.<anonymous> (/payload-3.0-alpha-demo/node_modules/cross-env/src/bin/cross-env.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}

**Comment by tomekwlod** [comment]
Exactly same problem here :-(

**Comment by twosixstudio** [comment]
And here!

**Comment by nckre** [comment]
Did you install/run via `npm`? For me installing + running via `pnpm` fixed this.

**Comment by twosixstudio** [comment]
Fixed me too, thank you :)

**Comment by tomekwlod** [comment]
I can confirm, `pnpm` did the trick

**Comment by jmikrut** [comment]
Could also be a peer dependencies issue with NPM.

If you want to use NPM, please try to install via `npm install --legacy-peer-deps` but we will try and get through this with a more effective permanent fix.

**Comment by jmikrut** [comment]
@denolfe this also may be fixed with the most recent alpha version. Will you try and close if it is indeed fixed now?
