### ISSUE TITLE
Version diff errors with: Warning: Cannot update a component (`HotReload`) while rendering a different component (`Select`).

### ISSUE THREAD

**Issue by remy90** [payloadcms/payload-3.0-alpha-demo#61]
Collection versions result in a white screen when you click on a specific version.

I'm not sure if this is a known issue but it's proven difficult to discover on discord if so.
Thought it worth mentioning for anyone else that may have accidentally come across this:

Steps to reproduce:
1. Use alpha 3.0 template: 
2. update the page collection to include versions:
```typescript
  {
      slug: 'pages',
      admin: {
        useAsTitle: 'title',
      },
      fields: [
        {
          name: 'title',
          type: 'text',
        },
        {
          name: 'content',
          type: 'richText',
        },
      ],
      versions: {
        drafts: true,
      },
    },
```
4. create a "page" via from /admin
5. make a change
6. add a title and save/publish.
7. Click versions > select the item that has just been saved
8. Observe the white screen of death

package manager:
`pnpm`

The repro above will likely be more helpful but. I've added the errors below:
```bash
Warning: Cannot update a component (`HotReload`) while rendering a different component (`Select`). To locate the bad setState() call inside `Select`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at Select (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/RenderFieldsToDiff/fields/Select/index.js:25:19)
    at div
    at div
    at RenderFieldsToDiff (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/RenderFieldsToDiff/index.js:10:11)
    at div
    at div
    at Iterable (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/RenderFieldsToDiff/fields/Iterable/index.js:13:21)
    at div
    at div
    at RenderFieldsToDiff (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/RenderFieldsToDiff/index.js:10:11)
    at div
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/elements/Gutter/index.js:9:13)
    at main
    at DefaultVersionView (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/Default/index.js:40:11)
    at VersionView (Server)
    at RenderCustomComponent (Server)
    at FormQueryParamsProvider (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/providers/FormQueryParams/index.js:14:11)
    at EditDepthProvider (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/providers/EditDepth/index.js:12:11)
    at DocumentInfoProvider (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/providers/DocumentInfo/index.js:36:11)
    at Document (Server)
    at div
    at div
    at Wrapper (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/templates/Default/Wrapper/index.js:12:13)
    at div
    at DefaultTemplate (Server)
    at Page (Server)
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:344:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:162:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:227:11)
```

```bash
Uncaught TypeError: Cannot read properties of undefined (reading 'find')
    at getOptionsToRender (index.js:17:20)
    at Select (index.js:28:89)
    at renderWithHooks (react-dom.development.js:11121:18)
    at mountIndeterminateComponent (react-dom.development.js:16869:13)
    at beginWork$1 (react-dom.development.js:18458:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at beginWork (react-dom.development.js:26949:7)
    at performUnitOfWork (react-dom.development.js:25748:12)
    at workLoopSync (react-dom.development.js:25464:5)
    at renderRootSync (react-dom.development.js:25419:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:24504:74)
    at workLoop (scheduler.development.js:256:34)
    at flushWork (scheduler.development.js:225:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:534:21)
```

```bash
The above error occurred in the <NotFoundErrorBoundary> component:

    at Select (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/RenderFieldsToDiff/fields/Select/index.js:25:19)
    at div
    at div
    at RenderFieldsToDiff (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/RenderFieldsToDiff/index.js:10:11)
    at div
    at div
    at Iterable (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/RenderFieldsToDiff/fields/Iterable/index.js:13:21)
    at div
    at div
    at RenderFieldsToDiff (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/RenderFieldsToDiff/index.js:10:11)
    at div
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/elements/Gutter/index.js:9:13)
    at main
    at DefaultVersionView (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+next@3.0.0-alpha.49_@types+react@18.2.66_http-status@1.6.2_monaco-editor@0.47.0_n_24h7zara5zlpxsbwmw4igtikji/node_modules/@payloadcms/next/dist/views/Version/Default/index.js:40:11)
    at VersionView (Server)
    at RenderCustomComponent (Server)
    at FormQueryParamsProvider (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/providers/FormQueryParams/index.js:14:11)
    at EditDepthProvider (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/providers/EditDepth/index.js:12:11)
    at DocumentInfoProvider (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/providers/DocumentInfo/index.js:36:11)
    at Document (Server)
    at div
    at div
    at Wrapper (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@payloadcms+ui@3.0.0-alpha.49_@types+react@18.2.66_monaco-editor@0.47.0_next@14.2.0-canary.23_nuu4tagqhpwxrkquwtubvbs2bu/node_modules/@payloadcms/ui/dist/templates/Default/Wrapper/index.js:12:13)
    at div
    at DefaultTemplate (Server)
    at Page (Server)
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:344:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:162:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/
```

**Comment by jacobsfletch** [comment]
Thanks for reporting this @remy90 👍 @PatrikKozak has a fixed for this already merged which will go out in the next alpha release.
